spring:
  application:
    name: digital-pdf-flatten-xfa
  cloud:
    function:
      definition: flattenPDF
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:localstack}
  main:
    web-application-type: none

logging:
  level:
    root: INFO
    za.co.ocr: DEBUG

aws:
  region: af-south-1
  dynamodb:
    table-name: ${AWS_DYNAMODB_TABLE_NAME:EmailInfo}

bpm:
  url: https://esbdpu.standardbank.co.za:4060/rest/bpm/wle/v1/service/ZACOTT@createPaymentTransaction?action=start&createTask=false&parts=all
  auth: ${BPM_AUTH:}
