spring:
  application:
    name: digital-pdf-flatten-xfa
  cloud:
    function:
      definition: flattenPDF

logging:
  level:
    root: INFO
    za.co.ocr: DEBUG

aws:
  sqs:
    endpoint: ${AWS_SQS_URI}
